{"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/vigramsdk\/authenticationerror\/failure(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failure"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError"]]},"kind":"symbol","abstract":[{"text":"Authentication is failure - Other error received from server","type":"text"}],"sections":[],"metadata":{"externalID":"s:9VigramSDK19AuthenticationErrorO7failureyACSScACmF","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failure"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"roleHeading":"Case","title":"AuthenticationError.failure(_:)","modules":[{"name":"VigramSDK"}],"symbolKind":"case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)"},"references":{"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError":{"kind":"symbol","url":"\/documentation\/vigramsdk\/authenticationerror","role":"symbol","navigatorTitle":[{"text":"AuthenticationError","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticationError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError","title":"AuthenticationError","abstract":[{"type":"text","text":"AuthenticationError contains custom failure events when connecting to Authentication process."}]},"doc://com.vigram.VigramSDK/documentation/VigramSDK":{"title":"VigramSDK","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","abstract":[],"kind":"symbol","images":[{"identifier":"logo.png","type":"icon"}],"role":"collection","url":"\/documentation\/vigramsdk","type":"topic"},"logo.png":{"type":"image","alt":"Vigram logo.","identifier":"logo.png","variants":[{"traits":["1x","light"],"url":"\/images\/com.vigram.VigramSDK\/logo.png"}]},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError/failure(_:)":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failure"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"AuthenticationError.failure(_:)","abstract":[{"type":"text","text":"Authentication is failure - Other error received from server"}],"type":"topic","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)","role":"symbol","url":"\/documentation\/vigramsdk\/authenticationerror\/failure(_:)"}}}