{"identifier":{"url":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/BluetoothServiceError\/notConnected(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/BluetoothServiceError"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"notConnected","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/vigramsdk\/bluetoothserviceerror\/notconnected(_:)"]}],"sections":[],"abstract":[{"type":"text","text":"Connecting to a device failed unexplicably."}],"metadata":{"title":"BluetoothServiceError.notConnected(_:)","role":"symbol","roleHeading":"Case","symbolKind":"case","externalID":"s:9VigramSDK21BluetoothServiceErrorO12notConnectedyAC10Foundation4UUIDVcACmF","modules":[{"name":"VigramSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notConnected"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"references":{"doc://com.vigram.VigramSDK/documentation/VigramSDK/BluetoothServiceError":{"kind":"symbol","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/BluetoothServiceError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"BluetoothServiceError","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"BluetoothServiceError","kind":"identifier"}],"title":"BluetoothServiceError","type":"topic","url":"\/documentation\/vigramsdk\/bluetoothserviceerror","abstract":[{"type":"text","text":"BluetoothServiceError lists different errors that can be propagated by "},{"type":"reference","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/BluetoothService","isActive":true},{"text":" implementations.","type":"text"}]},"logo.png":{"identifier":"logo.png","alt":"Vigram logo.","variants":[{"traits":["1x","light"],"url":"\/images\/com.vigram.VigramSDK\/logo.png"}],"type":"image"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/BluetoothService":{"title":"BluetoothService","abstract":[{"type":"text","text":"A BluetoothService is used to handle bluetooth connections."}],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/BluetoothService","url":"\/documentation\/vigramsdk\/bluetoothservice","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"BluetoothService","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"BluetoothService"}]},"doc://com.vigram.VigramSDK/documentation/VigramSDK/BluetoothServiceError/notConnected(_:)":{"title":"BluetoothServiceError.notConnected(_:)","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"notConnected"},{"text":"(","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":")"}],"url":"\/documentation\/vigramsdk\/bluetoothserviceerror\/notconnected(_:)","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/BluetoothServiceError\/notConnected(_:)","abstract":[{"type":"text","text":"Connecting to a device failed unexplicably."}]},"doc://com.vigram.VigramSDK/documentation/VigramSDK":{"kind":"symbol","title":"VigramSDK","role":"collection","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","images":[{"identifier":"logo.png","type":"icon"}],"url":"\/documentation\/vigramsdk","abstract":[],"type":"topic"}}}