{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"metadata":{"role":"symbol","externalID":"s:9VigramSDK19AuthenticationErrorO7failureyACSScACmF","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"failure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"roleHeading":"Case","modules":[{"name":"VigramSDK"}],"title":"AuthenticationError.failure(_:)","symbolKind":"case"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Authentication is failure - Other error received from server"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/vigramsdk\/authenticationerror\/failure(_:)"]}],"references":{"logo.png":{"type":"image","identifier":"logo.png","alt":"Vigram logo.","variants":[{"url":"\/images\/com.vigram.VigramSDK\/logo.png","traits":["1x","light"]}]},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError/failure(_:)":{"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failure","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/vigramsdk\/authenticationerror\/failure(_:)","abstract":[{"text":"Authentication is failure - Other error received from server","type":"text"}],"title":"AuthenticationError.failure(_:)"},"doc://com.vigram.VigramSDK/documentation/VigramSDK":{"role":"collection","title":"VigramSDK","kind":"symbol","images":[{"identifier":"logo.png","type":"icon"}],"abstract":[],"url":"\/documentation\/vigramsdk","type":"topic","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError":{"title":"AuthenticationError","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AuthenticationError"}],"type":"topic","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError","url":"\/documentation\/vigramsdk\/authenticationerror","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AuthenticationError"}],"abstract":[{"type":"text","text":"AuthenticationError contains custom failure events when connecting to Authentication process."}]}}}