{"identifier":{"url":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"case","roleHeading":"Case","title":"AuthenticationError.failure(_:)","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"failure","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"VigramSDK"}],"externalID":"s:9VigramSDK19AuthenticationErrorO7failureyACSScACmF","role":"symbol"},"abstract":[{"type":"text","text":"Authentication is failure - Other error received from server"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failure","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/vigramsdk\/authenticationerror\/failure(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.vigram.VigramSDK/documentation/VigramSDK":{"role":"collection","abstract":[],"images":[{"identifier":"logo.png","type":"icon"}],"url":"\/documentation\/vigramsdk","kind":"symbol","title":"VigramSDK","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","type":"topic"},"logo.png":{"alt":"Vigram logo.","type":"image","variants":[{"url":"\/images\/com.vigram.VigramSDK\/logo.png","traits":["1x","light"]}],"identifier":"logo.png"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError":{"kind":"symbol","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError","role":"symbol","abstract":[{"type":"text","text":"AuthenticationError contains custom failure events when connecting to Authentication process."}],"type":"topic","title":"AuthenticationError","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AuthenticationError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AuthenticationError"}],"url":"\/documentation\/vigramsdk\/authenticationerror"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError/failure(_:)":{"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failure"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"abstract":[{"text":"Authentication is failure - Other error received from server","type":"text"}],"title":"AuthenticationError.failure(_:)","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/vigramsdk\/authenticationerror\/failure(_:)"}}}