{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError"]]},"abstract":[{"type":"text","text":"Authentication is failure - Other error received from server"}],"metadata":{"roleHeading":"Case","modules":[{"name":"VigramSDK"}],"externalID":"s:9VigramSDK19AuthenticationErrorO7failureyACSScACmF","role":"symbol","title":"AuthenticationError.failure(_:)","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failure"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/vigramsdk\/authenticationerror\/failure(_:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)"},"references":{"doc://com.vigram.VigramSDK/documentation/VigramSDK":{"type":"topic","url":"\/documentation\/vigramsdk","abstract":[],"kind":"symbol","title":"VigramSDK","role":"collection","images":[{"identifier":"logo.png","type":"icon"}],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError/failure(_:)":{"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)","abstract":[{"type":"text","text":"Authentication is failure - Other error received from server"}],"kind":"symbol","role":"symbol","title":"AuthenticationError.failure(_:)","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failure"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/vigramsdk\/authenticationerror\/failure(_:)"},"logo.png":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.vigram.VigramSDK\/logo.png"}],"identifier":"logo.png","alt":"Vigram logo."},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError":{"type":"topic","role":"symbol","kind":"symbol","title":"AuthenticationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AuthenticationError","kind":"identifier"}],"navigatorTitle":[{"text":"AuthenticationError","kind":"identifier"}],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError","abstract":[{"type":"text","text":"AuthenticationError contains custom failure events when connecting to Authentication process."}],"url":"\/documentation\/vigramsdk\/authenticationerror"}}}