{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError"]]},"identifier":{"url":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Authentication is failure - Other error received from server"}],"metadata":{"externalID":"s:9VigramSDK19AuthenticationErrorO7failureyACSScACmF","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"name":"VigramSDK"}],"role":"symbol","roleHeading":"Case","title":"AuthenticationError.failure(_:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"failure","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/vigramsdk\/authenticationerror\/failure(_:)"]}],"references":{"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError/failure(_:)":{"kind":"symbol","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"role":"symbol","title":"AuthenticationError.failure(_:)","type":"topic","url":"\/documentation\/vigramsdk\/authenticationerror\/failure(_:)","abstract":[{"text":"Authentication is failure - Other error received from server","type":"text"}]},"doc://com.vigram.VigramSDK/documentation/VigramSDK":{"kind":"symbol","title":"VigramSDK","role":"collection","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","images":[{"identifier":"logo.png","type":"icon"}],"url":"\/documentation\/vigramsdk","abstract":[],"type":"topic"},"logo.png":{"type":"image","alt":"Vigram logo.","identifier":"logo.png","variants":[{"traits":["1x","light"],"url":"\/images\/com.vigram.VigramSDK\/logo.png"}]},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError":{"abstract":[{"text":"AuthenticationError contains custom failure events when connecting to Authentication process.","type":"text"}],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError","navigatorTitle":[{"text":"AuthenticationError","kind":"identifier"}],"url":"\/documentation\/vigramsdk\/authenticationerror","title":"AuthenticationError","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AuthenticationError"}]}}}